/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage, UITextInputTraits;

@interface UIKeyboard : UIView
{
    UIImage *m_snapshot;
    UITextInputTraits *m_defaultTraits;
}

+ (id)activeKeyboard;
+ (void)initImplementationNow;
+ (void)removeAllDynamicDictionaries;
+ (CGSize)defaultSize;
+ (CGSize)defaultSizeForInterfaceOrientation:(int)fp8;
+ (CGSize)defaultSizeForOrientation:(int)fp8;
- (id)initWithFrame:(CGRect)fp8;
- (id)initWithDefaultSize;
- (void)dealloc;
- (void)setFrame:(CGRect)fp8;
- (void)updateLayout;
- (int)orientation;
//- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)prepareForGeometryChange;
- (void)geometryChangeDone:(BOOL)fp8;
- (void)removeAutocorrectPrompt;
- (void)acceptAutocorrection;
- (void)setCaretBlinks:(BOOL)fp8;
- (void)setCaretVisible:(BOOL)fp8;
- (BOOL)returnKeyEnabled;
- (void)setReturnKeyEnabled:(BOOL)fp8;
- (id)defaultTextInputTraits;
- (void)setDefaultTextInputTraits:(id)fp8;
- (id)delegate;
- (void)clearSnapshot;
- (void)takeSnapshot;
- (void)activate;
- (void)deactivate;
- (void)movedFromSuperview:(id)fp8;
- (void)removeFromSuperview;
- (void)drawRect:(CGRect)fp8;
//- (void)mouseDown:(struct __GSEvent *)fp8;
//- (void)mouseUp:(struct __GSEvent *)fp8;
//- (void)mouseDragged:(struct __GSEvent *)fp8;
- (int)textEffectsVisibilityLevel;

@end


